global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
  - job_name: 'customer-api'
    static_configs:
      - targets: ['customer-api:3000']
  - job_name: 'customer-service'
    static_configs:
      - targets: ['customer-service:3003']
  - job_name: 'account-service'
    static_configs:
      - targets: ['account-service:3002']
  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:3004']
  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container

rule_files:
  - /etc/prometheus/rules/alerts.yml