apiVersion: 1

deleteDatasources:
  - name: Gemini Service
    orgId: 1

datasources:
  - name: Gemini Service
    type: marcusolsson-json-datasource
    access: proxy
    url: http://gemini-service:3001
    isDefault: true
    jsonData:
      queryParams: []
    version: 1
    editable: true 